spring:
  main:
    allow-bean-definition-overriding: true
  batch:
    job:
      enabled: false
      names: saveQuizAtRDBMSJob, makeDataStructureQuizJob, makeDataBaseQuizJob, makeJavaQuizJob, makeSpringQuizJob, makeNetworkQuizJob, makeInterviewQuizJob
    jdbc:
      initialize-schema: always
  datasource:
    hikari:
      maximum-pool-size: 20
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: true
    properties:
      hibernate:
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
        ddl-auto: update

openai:
  model: ${OPENAI_MODEL}
  api:
    url: ${OPENAI_URL}
    key: ${OPENAI_KEY}
server:
  port: 8081

