spring:
  main:
    allow-bean-definition-overriding: true
  batch:
    job:
      enabled: false
      names: saveQuizAtRDBMSJob, makeCQuizJob, makeDataBaseQuizJob, makeJavaQuizJob, makeSpringQuizJob, makeNetworkQuizJob, makeComputerScienceQuizJob, makeDjangoQuizJob, makePythonQuizJob, makeJavaScriptQuizJob, makeJPAQuizJob, makeLinuxQuizJob, makeReactQuizJob
    jdbc:
      initialize-schema: always
  datasource:
    hikari:
      maximum-pool-size: 20
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: true
    hibernate:
        ddl-auto: none

openai:
  model: ${OPENAI_MODEL}
  api:
    url: ${OPENAI_URL}
    key: ${OPENAI_KEY}
server:
  port: 8081

